export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          email: string;
          name: string;
          avatar_url: string | null;
          role: string;
          department: string | null;
          position: string | null;
          nextauth_migrated: boolean;
          nextauth_original_id: string | null;
          migration_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name: string;
          avatar_url?: string | null;
          role?: string;
          department?: string | null;
          position?: string | null;
          nextauth_migrated?: boolean;
          nextauth_original_id?: string | null;
          migration_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          avatar_url?: string | null;
          role?: string;
          department?: string | null;
          position?: string | null;
          nextauth_migrated?: boolean;
          nextauth_original_id?: string | null;
          migration_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      cost_records: {
        Row: {
          id: string;
          registration_date: string;
          start_date: string;
          code: string;
          team: string;
          assignee_id: string | null;
          cost_type: string;
          content: string;
          quantity: number;
          unit_price: number;
          amount: number;
          status: string;
          completion_date: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          registration_date: string;
          start_date: string;
          code: string;
          team: string;
          assignee_id?: string | null;
          cost_type: string;
          content: string;
          quantity?: number;
          unit_price: number;
          amount: number;
          status?: string;
          completion_date?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          registration_date?: string;
          start_date?: string;
          code?: string;
          team?: string;
          assignee_id?: string | null;
          cost_type?: string;
          content?: string;
          quantity?: number;
          unit_price?: number;
          amount?: number;
          status?: string;
          completion_date?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      task_records: {
        Row: {
          id: string;
          no: number;
          registration_date: string;
          code: string;
          team: string;
          department: string;
          work_content: string;
          status: string;
          assignee_id: string | null;
          start_date: string | null;
          completed_date: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          no?: number;
          registration_date: string;
          code: string;
          team: string;
          department: string;
          work_content: string;
          status?: string;
          assignee_id?: string | null;
          start_date?: string | null;
          completed_date?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          no?: number;
          registration_date?: string;
          code?: string;
          team?: string;
          department?: string;
          work_content?: string;
          status?: string;
          assignee_id?: string | null;
          start_date?: string | null;
          completed_date?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      education_records: {
        Row: {
          id: string;
          registration_date: string;
          start_date: string;
          code: string;
          education_type: string;
          content: string;
          participants: number;
          location: string;
          status: string;
          completion_date: string | null;
          assignee_id: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          registration_date: string;
          start_date: string;
          code: string;
          education_type: string;
          content: string;
          participants?: number;
          location: string;
          status?: string;
          completion_date?: string | null;
          assignee_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          registration_date?: string;
          start_date?: string;
          code?: string;
          education_type?: string;
          content?: string;
          participants?: number;
          location?: string;
          status?: string;
          completion_date?: string | null;
          assignee_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
